serviceMonitor:
  enabled: false

config:
  datasource:
    host: "book-shop-postgres.default.svc.cluster.local"
    user: "appuser"
    passwordSecret: 
      name: postgres-user-pass
      key: password
    port: "5432"
    database: "bookshop"
    sslmode: disable
  excludeDatabases: []

